var child = [
  { 'dupe': false, 'type': 4, 'name': 'feature-toggle', 'dir': 'c0', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/edit-post/build-module/components/header/feature-toggle/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'fullscreen-mode-close', 'dir': 'c1', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/edit-post/build-module/components/header/fullscreen-mode-close/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'header-toolbar', 'dir': 'c2', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/edit-post/build-module/components/header/header-toolbar/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'mode-switcher', 'dir': 'c3', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/edit-post/build-module/components/header/mode-switcher/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'more-menu', 'dir': 'c4', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/edit-post/build-module/components/header/more-menu/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'options-menu-item', 'dir': 'c5', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/edit-post/build-module/components/header/options-menu-item/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'pinned-plugins', 'dir': 'c6', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/edit-post/build-module/components/header/pinned-plugins/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'plugin-more-menu-item', 'dir': 'c7', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/edit-post/build-module/components/header/plugin-more-menu-item/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'plugin-sidebar-more-menu-item', 'dir': 'c8', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/edit-post/build-module/components/header/plugin-sidebar-more-menu-item/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'plugins-more-menu-group', 'dir': 'c9', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/edit-post/build-module/components/header/plugins-more-menu-group/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'tools-more-menu-group', 'dir': 'c10', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/edit-post/build-module/components/header/tools-more-menu-group/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'writing-menu', 'dir': 'c11', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/edit-post/build-module/components/header/writing-menu/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'index.js', 'dir': 'c12', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/edit-post/build-module/components/header/index.js', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'post-publish-button-or-toggle.js', 'dir': 'c13', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/edit-post/build-module/components/header/post-publish-button-or-toggle.js', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 }
];
