var child = [
  { 'dupe': false, 'type': 4, 'name': 'create-higher-order-component', 'dir': 'c0', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/compose/build-module/create-higher-order-component/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'if-condition', 'dir': 'c1', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/compose/build-module/if-condition/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'pure', 'dir': 'c2', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/compose/build-module/pure/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'with-global-events', 'dir': 'c3', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/compose/build-module/with-global-events/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 2, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'with-instance-id', 'dir': 'c4', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/compose/build-module/with-instance-id/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'with-safe-timeout', 'dir': 'c5', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/compose/build-module/with-safe-timeout/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'with-state', 'dir': 'c6', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/compose/build-module/with-state/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'index.js', 'dir': 'c7', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/compose/build-module/index.js', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 }
];
