var child = [
  { 'dupe': false, 'type': 4, 'name': 'dark_rounded', 'dir': 'c0', 'linked': 2, 'url': 'http://www.megacorpone.com/assets/css/images/prettyPhoto/dark_rounded/', 'fetched': true, 'code': 200, 'len': 1851, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': true, 'child_cnt': 7, 'issue_cnt': [ 3, 0, 0, 0, 0 ], 'sig': 0x9d188da6 },
  { 'dupe': false, 'type': 4, 'name': 'dark_square', 'dir': 'c1', 'linked': 2, 'url': 'http://www.megacorpone.com/assets/css/images/prettyPhoto/dark_square/', 'fetched': true, 'code': 200, 'len': 1632, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': true, 'child_cnt': 3, 'issue_cnt': [ 3, 0, 0, 0, 0 ], 'sig': 0x7920917f },
  { 'dupe': false, 'type': 4, 'name': 'default', 'dir': 'c2', 'linked': 2, 'url': 'http://www.megacorpone.com/assets/css/images/prettyPhoto/default/', 'fetched': true, 'code': 200, 'len': 2257, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': true, 'child_cnt': 8, 'issue_cnt': [ 3, 0, 0, 0, 0 ], 'sig': 0xb563014f },
  { 'dupe': false, 'type': 4, 'name': 'facebook', 'dir': 'c3', 'linked': 2, 'url': 'http://www.megacorpone.com/assets/css/images/prettyPhoto/facebook/', 'fetched': true, 'code': 200, 'len': 2753, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': true, 'child_cnt': 6, 'issue_cnt': [ 3, 0, 0, 0, 0 ], 'sig': 0x9b2b2a12 },
  { 'dupe': true, 'type': 4, 'name': 'light_rounded', 'dir': 'c4', 'linked': 2, 'url': 'http://www.megacorpone.com/assets/css/images/prettyPhoto/light_rounded/', 'fetched': true, 'code': 200, 'len': 1636, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': true, 'child_cnt': 3, 'issue_cnt': [ 2, 0, 0, 0, 0 ], 'sig': 0x7920917f },
  { 'dupe': false, 'type': 4, 'name': 'light_square', 'dir': 'c5', 'linked': 2, 'url': 'http://www.megacorpone.com/assets/css/images/prettyPhoto/light_square/', 'fetched': true, 'code': 200, 'len': 1433, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': true, 'child_cnt': 2, 'issue_cnt': [ 4, 0, 0, 0, 0 ], 'sig': 0x8ce658e9 },
  { 'dupe': false, 'type': 64, 'name': 'C=N', 'dir': 'c6', 'linked': 2, 'url': 'http://www.megacorpone.com/assets/css/images/prettyPhoto/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 2004, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 },
  { 'dupe': false, 'type': 64, 'name': 'O=D', 'dir': 'c7', 'linked': 2, 'url': 'http://www.megacorpone.com/assets/css/images/prettyPhoto/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 2004, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 }
];
