var child = [
  { 'dupe': false, 'type': 4, 'name': 'queried-data', 'dir': 'c0', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/core-data/build-module/queried-data/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 5, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'utils', 'dir': 'c1', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/core-data/build-module/utils/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 5, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'actions.js', 'dir': 'c2', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/core-data/build-module/actions.js', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'controls.js', 'dir': 'c3', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/core-data/build-module/controls.js', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'entities.js', 'dir': 'c4', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/core-data/build-module/entities.js', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'index.js', 'dir': 'c5', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/core-data/build-module/index.js', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'name.js', 'dir': 'c6', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/core-data/build-module/name.js', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'reducer.js', 'dir': 'c7', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/core-data/build-module/reducer.js', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'resolvers.js', 'dir': 'c8', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/core-data/build-module/resolvers.js', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'selectors.js', 'dir': 'c9', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/core-data/build-module/selectors.js', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 }
];
