var child = [
  { 'dupe': false, 'type': 4, 'name': 'bold', 'dir': 'c0', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/format-library/build-module/bold/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'code', 'dir': 'c1', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/format-library/build-module/code/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'image', 'dir': 'c2', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/format-library/build-module/image/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'italic', 'dir': 'c3', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/format-library/build-module/italic/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'link', 'dir': 'c4', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/format-library/build-module/link/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 3, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'strikethrough', 'dir': 'c5', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/format-library/build-module/strikethrough/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'underline', 'dir': 'c6', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/format-library/build-module/underline/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'default-formats.js', 'dir': 'c7', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/format-library/build-module/default-formats.js', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 32, 'name': 'index.js', 'dir': 'c8', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/format-library/build-module/index.js', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 }
];
