var child = [
  { 'dupe': true, 'type': 16, 'name': 'byte_safe_strings.php', 'dir': 'c0', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/random_compat/byte_safe_strings.php', 'fetched': true, 'code': 200, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': true, 'type': 16, 'name': 'cast_to_int.php', 'dir': 'c1', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/random_compat/cast_to_int.php', 'fetched': true, 'code': 200, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': true, 'type': 16, 'name': 'error_polyfill.php', 'dir': 'c2', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/random_compat/error_polyfill.php', 'fetched': true, 'code': 200, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': true, 'type': 16, 'name': 'random.php', 'dir': 'c3', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/random_compat/random.php', 'fetched': true, 'code': 200, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': true, 'type': 16, 'name': 'random_bytes_dev_urandom.php', 'dir': 'c5', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/random_compat/random_bytes_dev_urandom.php', 'fetched': true, 'code': 200, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': true, 'type': 16, 'name': 'random_bytes_libsodium.php', 'dir': 'c6', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/random_compat/random_bytes_libsodium.php', 'fetched': true, 'code': 200, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': true, 'type': 16, 'name': 'random_bytes_mcrypt.php', 'dir': 'c8', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/random_compat/random_bytes_mcrypt.php', 'fetched': true, 'code': 200, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': true, 'type': 16, 'name': 'random_int.php', 'dir': 'c9', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/random_compat/random_int.php', 'fetched': true, 'code': 200, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': false, 'type': 64, 'name': 'C=N', 'dir': 'c10', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/random_compat/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 3039, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 },
  { 'dupe': false, 'type': 64, 'name': 'O=D', 'dir': 'c11', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/random_compat/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 3039, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 }
];
