var child = [
  { 'dupe': true, 'type': 4, 'name': 'class-wp-rest-comment-meta-fields.php', 'dir': 'c0', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/rest-api/fields/class-wp-rest-comment-meta-fields.php/', 'fetched': true, 'code': 500, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff9861c },
  { 'dupe': true, 'type': 4, 'name': 'class-wp-rest-post-meta-fields.php', 'dir': 'c1', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/rest-api/fields/class-wp-rest-post-meta-fields.php/', 'fetched': true, 'code': 500, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff9861c },
  { 'dupe': true, 'type': 4, 'name': 'class-wp-rest-term-meta-fields.php', 'dir': 'c2', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/rest-api/fields/class-wp-rest-term-meta-fields.php/', 'fetched': true, 'code': 500, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff9861c },
  { 'dupe': true, 'type': 4, 'name': 'class-wp-rest-user-meta-fields.php', 'dir': 'c3', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/rest-api/fields/class-wp-rest-user-meta-fields.php/', 'fetched': true, 'code': 500, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff9861c },
  { 'dupe': true, 'type': 16, 'name': 'class-wp-rest-meta-fields.php', 'dir': 'c4', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/rest-api/fields/class-wp-rest-meta-fields.php', 'fetched': true, 'code': 200, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': false, 'type': 64, 'name': 'C=N', 'dir': 'c5', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/rest-api/fields/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 2053, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 },
  { 'dupe': false, 'type': 64, 'name': 'O=D', 'dir': 'c6', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/rest-api/fields/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 2053, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 }
];
