var child = [
  { 'dupe': false, 'type': 8, 'name': 'border-anim-h.gif', 'dir': 'c0', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/js/imgareaselect/border-anim-h.gif', 'fetched': true, 'code': 200, 'len': 178, 'decl_mime': 'image/gif', 'sniff_mime': 'image/gif', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': true, 'type': 8, 'name': 'border-anim-v.gif', 'dir': 'c1', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/js/imgareaselect/border-anim-v.gif', 'fetched': true, 'code': 200, 'len': 178, 'decl_mime': 'image/gif', 'sniff_mime': 'image/gif', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': false, 'type': 8, 'name': 'imgareaselect.css', 'dir': 'c2', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/js/imgareaselect/imgareaselect.css', 'fetched': true, 'code': 200, 'len': 790, 'decl_mime': 'text/css', 'sniff_mime': 'text/css', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': false, 'type': 8, 'name': 'jquery.imgareaselect.js', 'dir': 'c3', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/js/imgareaselect/jquery.imgareaselect.js', 'fetched': true, 'code': 200, 'len': 38132, 'decl_mime': 'application/javascript', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': false, 'type': 8, 'name': 'jquery.imgareaselect.min.js', 'dir': 'c4', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/js/imgareaselect/jquery.imgareaselect.min.js', 'fetched': true, 'code': 200, 'len': 9887, 'decl_mime': 'application/javascript', 'sniff_mime': 'text/html', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 2, 0, 0, 0, 0 ], 'sig': 0xc5c4f230 },
  { 'dupe': false, 'type': 64, 'name': 'C=N', 'dir': 'c5', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/js/imgareaselect/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 1910, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 },
  { 'dupe': false, 'type': 64, 'name': 'O=D', 'dir': 'c6', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/js/imgareaselect/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 1910, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 }
];
