var child = [
  { 'dupe': true, 'type': 4, 'name': '', 'dir': 'c0', 'linked': 0, 'url': 'http://10.11.1.251/icons/small//', 'fetched': true, 'code': 403, 'len': 276, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'iso-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfffbffff },
  { 'dupe': true, 'type': 4, 'name': '.php', 'dir': 'c1', 'linked': 0, 'url': 'http://10.11.1.251/icons/small/.php/', 'fetched': true, 'code': 403, 'len': 276, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'iso-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff8d75a },
  { 'dupe': false, 'type': 8, 'name': 'back.gif', 'dir': 'c2', 'linked': 0, 'url': 'http://10.11.1.251/icons/small/back.gif', 'fetched': true, 'code': 200, 'len': 129, 'decl_mime': 'image/gif', 'sniff_mime': 'image/gif', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': false, 'type': 8, 'name': 'blank.gif', 'dir': 'c4', 'linked': 0, 'url': 'http://10.11.1.251/icons/small/blank.gif', 'fetched': true, 'code': 200, 'len': 55, 'decl_mime': 'image/gif', 'sniff_mime': 'image/gif', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': true, 'type': 8, 'name': 'folder.gif', 'dir': 'c6', 'linked': 0, 'url': 'http://10.11.1.251/icons/small/folder.gif', 'fetched': true, 'code': 200, 'len': 132, 'decl_mime': 'image/gif', 'sniff_mime': 'image/gif', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': true, 'type': 8, 'name': 'image.gif', 'dir': 'c8', 'linked': 0, 'url': 'http://10.11.1.251/icons/small/image.gif', 'fetched': true, 'code': 200, 'len': 126, 'decl_mime': 'image/gif', 'sniff_mime': 'image/gif', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': false, 'type': 8, 'name': 'index.gif', 'dir': 'c10', 'linked': 0, 'url': 'http://10.11.1.251/icons/small/index.gif', 'fetched': true, 'code': 200, 'len': 145, 'decl_mime': 'image/gif', 'sniff_mime': 'image/gif', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': true, 'type': 8, 'name': 'text.gif', 'dir': 'c12', 'linked': 0, 'url': 'http://10.11.1.251/icons/small/text.gif', 'fetched': true, 'code': 200, 'len': 128, 'decl_mime': 'image/gif', 'sniff_mime': 'image/gif', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': false, 'type': 8, 'name': 'unknown.gif', 'dir': 'c14', 'linked': 0, 'url': 'http://10.11.1.251/icons/small/unknown.gif', 'fetched': true, 'code': 200, 'len': 131, 'decl_mime': 'image/gif', 'sniff_mime': 'image/gif', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
];
