var child = [
  { 'dupe': false, 'type': 8, 'name': 'editor-rtl.css', 'dir': 'c0', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/css/dist/block-library/editor-rtl.css', 'fetched': true, 'code': 200, 'len': 40518, 'decl_mime': 'text/css', 'sniff_mime': 'text/css', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': true, 'type': 8, 'name': 'editor.css', 'dir': 'c2', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/css/dist/block-library/editor.css', 'fetched': true, 'code': 200, 'len': 40596, 'decl_mime': 'text/css', 'sniff_mime': 'text/css', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': false, 'type': 8, 'name': 'style-rtl.css', 'dir': 'c4', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/css/dist/block-library/style-rtl.css', 'fetched': true, 'code': 200, 'len': 35926, 'decl_mime': 'text/css', 'sniff_mime': 'text/css', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': true, 'type': 8, 'name': 'style.css', 'dir': 'c6', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/css/dist/block-library/style.css', 'fetched': true, 'code': 200, 'len': 36153, 'decl_mime': 'text/css', 'sniff_mime': 'text/css', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': false, 'type': 8, 'name': 'style.min.css', 'dir': 'c7', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/css/dist/block-library/style.min.css', 'fetched': true, 'code': 200, 'len': 29295, 'decl_mime': 'text/css', 'sniff_mime': 'text/css', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 2, 0, 0, 0, 0 ], 'sig': 0x7a2a5dce },
  { 'dupe': false, 'type': 8, 'name': 'theme-rtl.css', 'dir': 'c8', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/css/dist/block-library/theme-rtl.css', 'fetched': true, 'code': 200, 'len': 2496, 'decl_mime': 'text/css', 'sniff_mime': 'text/css', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': true, 'type': 8, 'name': 'theme.css', 'dir': 'c10', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/css/dist/block-library/theme.css', 'fetched': true, 'code': 200, 'len': 2493, 'decl_mime': 'text/css', 'sniff_mime': 'text/css', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': false, 'type': 8, 'name': 'theme.min.css', 'dir': 'c11', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/css/dist/block-library/theme.min.css', 'fetched': true, 'code': 200, 'len': 1495, 'decl_mime': 'text/css', 'sniff_mime': 'text/css', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 2, 0, 0, 0, 0 ], 'sig': 0x7a2a5dce },
  { 'dupe': false, 'type': 64, 'name': 'C=N', 'dir': 'c12', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/css/dist/block-library/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 3282, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 },
  { 'dupe': false, 'type': 64, 'name': 'O=D', 'dir': 'c13', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/css/dist/block-library/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 3282, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 }
];
