var child = [
  { 'dupe': false, 'type': 4, 'name': 'alignment-toolbar', 'dir': 'c0', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/block-editor/build-module/components/alignment-toolbar/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'autocomplete', 'dir': 'c1', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/block-editor/build-module/components/autocomplete/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'block-alignment-toolbar', 'dir': 'c2', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/block-editor/build-module/components/block-alignment-toolbar/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'block-controls', 'dir': 'c3', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/block-editor/build-module/components/block-controls/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'block-edit', 'dir': 'c4', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/block-editor/build-module/components/block-edit/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 3, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'block-format-controls', 'dir': 'c5', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/block-editor/build-module/components/block-format-controls/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'block-icon', 'dir': 'c6', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/block-editor/build-module/components/block-icon/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'block-navigation', 'dir': 'c7', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/block-editor/build-module/components/block-navigation/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 2, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'color-palette', 'dir': 'c8', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/block-editor/build-module/components/color-palette/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 2, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 },
  { 'dupe': false, 'type': 4, 'name': 'colors', 'dir': 'c9', 'linked': 1, 'url': 'http://10.11.1.251/wp/wp-includes/js/dist/node_modules/@wordpress/block-editor/build-module/components/colors/', 'fetched': false, 'error': 'Content not fetched', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x0 }
];
