var child = [
  { 'dupe': false, 'type': 8, 'name': 'archive.png', 'dir': 'c0', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/images/crystal/archive.png', 'fetched': true, 'code': 200, 'len': 2454, 'decl_mime': 'image/png', 'sniff_mime': 'image/png', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': false, 'type': 8, 'name': 'audio.png', 'dir': 'c1', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/images/crystal/audio.png', 'fetched': true, 'code': 200, 'len': 2184, 'decl_mime': 'image/png', 'sniff_mime': 'image/png', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': false, 'type': 8, 'name': 'code.png', 'dir': 'c2', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/images/crystal/code.png', 'fetched': true, 'code': 200, 'len': 1604, 'decl_mime': 'image/png', 'sniff_mime': 'image/png', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': false, 'type': 8, 'name': 'default.png', 'dir': 'c3', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/images/crystal/default.png', 'fetched': true, 'code': 200, 'len': 453, 'decl_mime': 'image/png', 'sniff_mime': 'image/png', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': false, 'type': 8, 'name': 'document.png', 'dir': 'c4', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/images/crystal/document.png', 'fetched': true, 'code': 200, 'len': 2063, 'decl_mime': 'image/png', 'sniff_mime': 'image/png', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': false, 'type': 8, 'name': 'interactive.png', 'dir': 'c5', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/images/crystal/interactive.png', 'fetched': true, 'code': 200, 'len': 2217, 'decl_mime': 'image/png', 'sniff_mime': 'image/png', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': false, 'type': 8, 'name': 'license.txt', 'dir': 'c6', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/images/crystal/license.txt', 'fetched': true, 'code': 200, 'len': 149, 'decl_mime': 'text/plain', 'sniff_mime': 'text/plain', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 2, 0, 0, 0, 0 ], 'sig': 0xd6bfd33e },
  { 'dupe': false, 'type': 8, 'name': 'spreadsheet.png', 'dir': 'c7', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/images/crystal/spreadsheet.png', 'fetched': true, 'code': 200, 'len': 2408, 'decl_mime': 'image/png', 'sniff_mime': 'image/png', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': false, 'type': 8, 'name': 'text.png', 'dir': 'c8', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/images/crystal/text.png', 'fetched': true, 'code': 200, 'len': 670, 'decl_mime': 'image/png', 'sniff_mime': 'image/png', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': false, 'type': 8, 'name': 'video.png', 'dir': 'c9', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/images/crystal/video.png', 'fetched': true, 'code': 200, 'len': 1339, 'decl_mime': 'image/png', 'sniff_mime': 'image/png', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': false, 'type': 64, 'name': 'C=N', 'dir': 'c10', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/images/crystal/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 2824, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 },
  { 'dupe': false, 'type': 64, 'name': 'O=D', 'dir': 'c11', 'linked': 2, 'url': 'http://10.11.1.251/wp/wp-includes/images/crystal/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 2824, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 }
];
