var child = [
  { 'dupe': false, 'type': 4, 'name': 'css', 'dir': 'c0', 'linked': 2, 'url': 'https://www.megacorpone.com/assets/css/', 'fetched': true, 'code': 200, 'len': 1966, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': true, 'child_cnt': 22, 'issue_cnt': [ 25, 3, 0, 0, 0 ], 'sig': 0x3958b002 },
  { 'dupe': true, 'type': 4, 'name': 'fonts', 'dir': 'c1', 'linked': 2, 'url': 'https://www.megacorpone.com/assets/fonts/', 'fetched': true, 'code': 200, 'len': 2852, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': true, 'child_cnt': 8, 'issue_cnt': [ 4, 0, 0, 0, 0 ], 'sig': 0x9ea3511f },
  { 'dupe': true, 'type': 4, 'name': 'ico', 'dir': 'c2', 'linked': 2, 'url': 'https://www.megacorpone.com/assets/ico/', 'fetched': true, 'code': 404, 'len': 295, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'iso-8859-1', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xdf0d3dce },
  { 'dupe': true, 'type': 4, 'name': 'images', 'dir': 'c3', 'linked': 1, 'url': 'https://www.megacorpone.com/assets/images/', 'fetched': true, 'code': 404, 'len': 298, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'iso-8859-1', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x20f2c231 },
  { 'dupe': false, 'type': 4, 'name': 'img', 'dir': 'c4', 'linked': 2, 'url': 'https://www.megacorpone.com/assets/img/', 'fetched': true, 'code': 200, 'len': 3956, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': true, 'child_cnt': 11, 'issue_cnt': [ 12, 2, 0, 0, 0 ], 'sig': 0x8de9d0d0 },
  { 'dupe': true, 'type': 4, 'name': 'js', 'dir': 'c5', 'linked': 2, 'url': 'https://www.megacorpone.com/assets/js/', 'fetched': true, 'code': 200, 'len': 2246, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': true, 'child_cnt': 6, 'issue_cnt': [ 6, 0, 0, 0, 0 ], 'sig': 0x7a434845 },
  { 'dupe': false, 'type': 64, 'name': 'C=N', 'dir': 'c6', 'linked': 2, 'url': 'https://www.megacorpone.com/assets/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 1475, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 },
  { 'dupe': false, 'type': 64, 'name': 'O=D', 'dir': 'c7', 'linked': 2, 'url': 'https://www.megacorpone.com/assets/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 1475, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 }
];
