var child = [
  { 'dupe': false, 'type': 4, 'name': 'clients', 'dir': 'c0', 'linked': 2, 'url': 'https://www.megacorpone.com/assets/img/clients/', 'fetched': true, 'code': 200, 'len': 1572, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': true, 'child_cnt': 2, 'issue_cnt': [ 3, 1, 0, 0, 0 ], 'sig': 0xef823832 },
  { 'dupe': true, 'type': 4, 'name': 'portfolio', 'dir': 'c1', 'linked': 2, 'url': 'https://www.megacorpone.com/assets/img/portfolio/', 'fetched': true, 'code': 200, 'len': 3501, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': true, 'child_cnt': 2, 'issue_cnt': [ 2, 0, 0, 0, 0 ], 'sig': 0xa442210c },
  { 'dupe': true, 'type': 4, 'name': 'team', 'dir': 'c2', 'linked': 2, 'url': 'https://www.megacorpone.com/assets/img/team/', 'fetched': true, 'code': 200, 'len': 2726, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': true, 'child_cnt': 4, 'issue_cnt': [ 4, 0, 0, 0, 0 ], 'sig': 0xa2dafea0 },
  { 'dupe': true, 'type': 8, 'name': 'agency.jpg', 'dir': 'c3', 'linked': 2, 'url': 'https://www.megacorpone.com/assets/img/agency.jpg', 'fetched': true, 'code': 200, 'len': 170409, 'decl_mime': 'image/jpeg', 'sniff_mime': 'image/jpeg', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': true, 'type': 8, 'name': 'browser.png', 'dir': 'c4', 'linked': 2, 'url': 'https://www.megacorpone.com/assets/img/browser.png', 'fetched': true, 'code': 200, 'len': 215866, 'decl_mime': 'image/png', 'sniff_mime': 'image/png', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': true, 'type': 8, 'name': 'contact.jpg', 'dir': 'c5', 'linked': 2, 'url': 'https://www.megacorpone.com/assets/img/contact.jpg', 'fetched': true, 'code': 200, 'len': 203460, 'decl_mime': 'image/jpeg', 'sniff_mime': 'image/jpeg', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': true, 'type': 8, 'name': 'nanowoman.jpg', 'dir': 'c7', 'linked': 2, 'url': 'https://www.megacorpone.com/assets/img/nanowoman.jpg', 'fetched': true, 'code': 200, 'len': 223876, 'decl_mime': 'image/jpeg', 'sniff_mime': 'image/jpeg', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': true, 'type': 8, 'name': 'post01.jpg', 'dir': 'c8', 'linked': 2, 'url': 'https://www.megacorpone.com/assets/img/post01.jpg', 'fetched': true, 'code': 200, 'len': 66956, 'decl_mime': 'image/jpeg', 'sniff_mime': 'image/jpeg', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': true, 'type': 8, 'name': 'post02.jpg', 'dir': 'c9', 'linked': 2, 'url': 'https://www.megacorpone.com/assets/img/post02.jpg', 'fetched': true, 'code': 200, 'len': 51441, 'decl_mime': 'image/jpeg', 'sniff_mime': 'image/jpeg', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': true, 'type': 8, 'name': 'post03.jpg', 'dir': 'c10', 'linked': 2, 'url': 'https://www.megacorpone.com/assets/img/post03.jpg', 'fetched': true, 'code': 200, 'len': 59382, 'decl_mime': 'image/jpeg', 'sniff_mime': 'image/jpeg', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': true, 'type': 8, 'name': 't-back.jpg', 'dir': 'c11', 'linked': 2, 'url': 'https://www.megacorpone.com/assets/img/t-back.jpg', 'fetched': true, 'code': 200, 'len': 246480, 'decl_mime': 'image/jpeg', 'sniff_mime': 'image/jpeg', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': true, 'type': 8, 'name': 'thumb01.jpg', 'dir': 'c12', 'linked': 2, 'url': 'https://www.megacorpone.com/assets/img/thumb01.jpg', 'fetched': true, 'code': 200, 'len': 18751, 'decl_mime': 'image/jpeg', 'sniff_mime': 'image/jpeg', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': true, 'type': 8, 'name': 'thumb02.jpg', 'dir': 'c13', 'linked': 2, 'url': 'https://www.megacorpone.com/assets/img/thumb02.jpg', 'fetched': true, 'code': 200, 'len': 12245, 'decl_mime': 'image/jpeg', 'sniff_mime': 'image/jpeg', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': true, 'type': 8, 'name': 'thumb03.jpg', 'dir': 'c14', 'linked': 2, 'url': 'https://www.megacorpone.com/assets/img/thumb03.jpg', 'fetched': true, 'code': 200, 'len': 12768, 'decl_mime': 'image/jpeg', 'sniff_mime': 'image/jpeg', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': true, 'type': 8, 'name': 'thumb04.jpg', 'dir': 'c15', 'linked': 2, 'url': 'https://www.megacorpone.com/assets/img/thumb04.jpg', 'fetched': true, 'code': 200, 'len': 11111, 'decl_mime': 'image/jpeg', 'sniff_mime': 'image/jpeg', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': false, 'type': 64, 'name': 'C=N', 'dir': 'c16', 'linked': 2, 'url': 'https://www.megacorpone.com/assets/img/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 3956, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x28f4fa31 },
  { 'dupe': false, 'type': 64, 'name': 'O=D', 'dir': 'c17', 'linked': 2, 'url': 'https://www.megacorpone.com/assets/img/?C=N;O=D', 'fetched': true, 'code': 200, 'len': 3956, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 1, 0, 0, 0 ], 'sig': 0xdcb52248 }
];
